import { useState } from 'react';
import api from '../api/axiosConfig';
import './AnnualReport.css';
const money = (v) => Number(v || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function AnnualReport() {
  const [fromDate, setFromDate] = useState(''); const [toDate, setToDate] = useState(''); const [report, setReport] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = async (e) => { e.preventDefault(); setLoading(true); setError(''); try { const { data } = await api.get('/annual-report', { params: { fromDate, toDate } }); setReport(data); } catch (err) { setError(err.response?.data?.message || 'Unable to load annual report.'); setReport(null); } finally { setLoading(false); } };
  return <section className="annual-report"><h2>Annual Report</h2><p>Bank account code 11: opening balance plus income, less expenses, for the selected period.</p><form onSubmit={load}><label>Start date<input type="date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} /></label><label>End date<input type="date" value={toDate} onChange={(e) => setToDate(e.target.value)} /></label><button disabled={loading}>{loading ? 'Loading...' : 'View Report'}</button></form>{error && <div className="error">{error}</div>}{report && <div className="excel-wrap"><table className="excel-table"><thead><tr><th colSpan="2">ANNUAL REPORT — {report.bank.accountTitle}</th></tr><tr><th>Account Title</th><th className="amount">Amount</th></tr></thead><tbody><tr className="opening"><td>Opening Balance (OB)</td><td className="amount">{money(report.openingBalance)}</td></tr><tr className="bank"><td>{report.bank.accountTitle} — Income / Profit</td><td className="amount">{money(report.incomeTotal)}</td></tr><tr className="subtotal"><td>Total Available Funds</td><td className="amount">{money(report.openingBalance + report.incomeTotal)}</td></tr><tr className="section"><td colSpan="2">Expenses</td></tr>{report.expenseRows.length ? report.expenseRows.map((row) => <tr key={row.accountId}><td>{row.accountTitle}</td><td className="amount">{money(row.amount)}</td></tr>) : <tr><td colSpan="2" className="empty">No expenses found.</td></tr>}<tr className="subtotal"><td>Total Expenses</td><td className="amount">{money(report.expenseTotal)}</td></tr><tr className="closing"><td>Current Balance (CB)</td><td className="amount">{money(report.closingBalance)}</td></tr></tbody></table></div>}</section>;
}
