import { useState } from 'react';
import api from '../api/axiosConfig';
import './ProfitLoss.css';

const money = (v) => Number(v || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const dateText = (v) => new Date(v).toLocaleDateString();
const escapeHtml = (v) => String(v ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));

export default function ProfitLoss() {
  const [fromDate, setFromDate] = useState(''); const [toDate, setToDate] = useState(''); const [report, setReport] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const load = async (e) => { e.preventDefault(); setLoading(true); setError(''); try { const { data } = await api.get('/profit-loss', { params: { fromDate: fromDate || undefined, toDate: toDate || undefined } }); setReport(data); } catch (err) { setError(err.response?.data?.message || 'Unable to load Profit & Loss.'); setReport(null); } finally { setLoading(false); } };
  const print = () => { if (!report) return; const period = fromDate && toDate ? `${dateText(fromDate)} to ${dateText(toDate)}` : 'All dates'; const section = (title, rows, total) => `<h2>${title}</h2><table><thead><tr><th>Sr.</th><th>Account Title</th><th class="amount">Amount</th></tr></thead><tbody>${rows.length ? rows.map((row, i) => `<tr><td>${i + 1}</td><td>${escapeHtml(row.accountName)}</td><td class="amount">${money(row.amount)}</td></tr>`).join('') : '<tr><td colspan="3">No entries</td></tr>'}</tbody><tfoot><tr><td colspan="2">Total ${title}</td><td class="amount">${money(total)}</td></tr></tfoot></table>`; const w = window.open('', '_blank', 'width=900,height=800'); if (!w) { setError('Please allow pop-ups to print the Profit & Loss report.'); return; } w.document.write(`<!doctype html><html><head><title>Profit and Loss</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#172033}.head{border-bottom:3px solid #2563eb;padding-bottom:16px}.logo{display:inline-grid;place-items:center;width:42px;height:42px;border-radius:9px;background:#2563eb;color:#fff;font-weight:800;margin-right:10px}.title{text-align:center;margin:24px 0 8px}.period{text-align:center;color:#64748b;margin-bottom:22px}h2{font-size:17px;margin:24px 0 8px}table{width:100%;border-collapse:collapse}th,td{padding:9px;border:1px solid #cbd5e1;text-align:left}th{background:#eaf1ff}.amount{text-align:right}tfoot{font-weight:700;background:#eff6ff}.profit{margin-top:24px;padding:16px;text-align:right;background:#dcfce7;font-size:18px;font-weight:800}@media print{@page{margin:12mm}body{padding:0}}</style></head><body><div class="head"><span class="logo">AA</span><strong>Accounting App</strong></div><h1 class="title">PROFIT &amp; LOSS</h1><div class="period">Period: ${escapeHtml(period)}<br>Created: ${escapeHtml(new Date().toLocaleString())}</div>${section('Income', report.income, report.totalIncome)}${section('Expenses', report.expenses, report.totalExpenses)}<div class="profit">${report.profit >= 0 ? 'Profit' : 'Loss'}: ${money(Math.abs(report.profit))}</div></body></html>`); w.document.close(); w.focus(); w.print(); };
  const rows = (items) => items.length ? items.map((r, i) => <tr key={r.accountId}><td>{i + 1}</td><td>{r.accountName}{r.headGroup && <small className="head-group">{r.headGroup}</small>}</td><td className="amount">{money(r.amount)}</td></tr>) : <tr><td colSpan="3" className="empty">No entries found.</td></tr>;
  return <section className="profit-loss"><h2>Profit &amp; Loss</h2><p>Income and expenses from your posted vouchers.</p><form onSubmit={load}><label>From date<input type="date" value={fromDate} onChange={(e) => setFromDate(e.target.value)} /></label><label>End date<input type="date" value={toDate} onChange={(e) => setToDate(e.target.value)} /></label><button disabled={loading}>{loading ? 'Loading...' : 'View Report'}</button></form>{error && <div className="error">{error}</div>}{report && <><section className="pl-section"><h3>Income</h3><table><thead><tr><th>Sr.</th><th>Account Title</th><th className="amount">Amount</th></tr></thead><tbody>{rows(report.income)}</tbody><tfoot><tr><td colSpan="2">Total Income</td><td className="amount">{money(report.totalIncome)}</td></tr></tfoot></table></section><section className="pl-section"><h3>Expenses</h3><table><thead><tr><th>Sr.</th><th>Account Title</th><th className="amount">Amount</th></tr></thead><tbody>{rows(report.expenses)}</tbody><tfoot><tr><td colSpan="2">Total Expenses</td><td className="amount">{money(report.totalExpenses)}</td></tr></tfoot></table></section><div className={`profit ${report.profit < 0 ? 'loss' : ''}`}><span>{report.profit >= 0 ? 'Profit' : 'Loss'}</span><strong>{money(Math.abs(report.profit))}</strong></div><div className="actions"><button type="button" onClick={print}>Print Profit &amp; Loss</button></div></>}</section>;
}
